# Build stage
FROM node:23.8-alpine AS builder
WORKDIR /build
COPY FrontendWeb/package*.json ./
RUN npm ci
COPY FrontendWeb . 
RUN npm run build

# Production stage
FROM nginx:alpine
COPY FrontendWeb/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
