server {
    listen       80;
    listen  [::]:80;

    location ~* \.js$ {
        root   /usr/share/nginx/html;
        add_header Content-Type application/javascript;
    }

    location ~* \.css$ {
        root   /usr/share/nginx/html;
        add_header Content-Type text/css;
    }

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}